FROM python:3.11
WORKDIR /code
COPY ./requirements/development.txt /code/requirements.txt
RUN pip install -r /code/requirements.txt
# COPY ./api-sivrg.crt /code/
# COPY ./api-sivrg.key /code/
COPY ./sql_app /code/
# CMD ["uvicorn", "main:app", "--proxy-headers", "--host", "0.0.0.0", "--port", "8443", "--ssl-keyfile", "api-sivrg.key", "--ssl-certfile", "api-sivrg.crt"]
CMD ["uvicorn", "main:app", "--proxy-headers", "--host", "0.0.0.0", "--port", "8443"]
