"""Delete pesada turno_id FK

Revision ID: c1651a784d60
Revises: abe3945fe358
Create Date: 2024-03-31 16:43:31.075014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1651a784d60'
down_revision: Union[str, None] = 'abe3945fe358'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('pesadas_turno_id_fkey', 'pesadas', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('pesadas_turno_id_fkey', 'pesadas', 'turnos', ['turno_id'], ['id'])
    # ### end Alembic commands ###
