"""Change silos estado column name

Revision ID: abe3945fe358
Revises: 9784eea2336a
Create Date: 2024-03-24 16:34:48.196033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abe3945fe358'
down_revision: Union[str, None] = '9784eea2336a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('silos', sa.Column('habilitado', sa.Boolean(), nullable=False))
    op.drop_column('silos', 'estado')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('silos', sa.Column('estado', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('silos', 'habilitado')
    # ### end Alembic commands ###
