"""Add pesada id to turnos table

Revision ID: 9784eea2336a
Revises: 2ff13581696f
Create Date: 2024-03-24 18:58:59.883958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9784eea2336a'
down_revision: Union[str, None] = '2ff13581696f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_pesada_per_turno', 'pesadas', type_='unique')
    op.add_column('turnos', sa.Column('checking_time', sa.TIMESTAMP(), nullable=True))
    op.add_column('turnos', sa.Column('pesada_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'turnos', 'pesadas', ['pesada_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'turnos', type_='foreignkey')
    op.drop_column('turnos', 'pesada_id')
    op.drop_column('turnos', 'checking_time')
    op.create_unique_constraint('unique_pesada_per_turno', 'pesadas', ['turno_id'])
    # ### end Alembic commands ###
