FROM node:18 as build

WORKDIR /app
COPY . /app/

RUN npm install
RUN npm install axios
RUN npm run build

FROM ubuntu:latest
RUN apt-get update
RUN apt-get install nginx -y
COPY --from=build /app/dist /var/www/html/
EXPOSE 80
CMD ["nginx","-g","daemon off;"]
