FROM node:18 as build

WORKDIR /app
COPY ./frontend /app/

RUN npm install
RUN npm install axios
RUN npm run build

FROM bitnami/nginx
COPY --from=build /app/dist /app/html-methizul.com.ar/

EXPOSE 8080

COPY ./nginx/sivrg.methizul.com.ar.conf /opt/bitnami/nginx/conf/server_blocks/sivrg.methizul.com.ar.conf
