"""1st

Revision ID: a48650488587
Revises: 
Create Date: 2023-10-18 22:52:42.664375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a48650488587'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresas',
    sa.Column('empresa_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('empresa_nombre', sa.String(length=255), nullable=False),
    sa.Column('empresa_RS', sa.String(length=255), nullable=False),
    sa.Column('empresa_CUIT', sa.String(length=255), nullable=False),
    sa.Column('empresa_direccion', sa.String(length=255), nullable=False),
    sa.Column('empresa_localidad', sa.String(length=255), nullable=False),
    sa.Column('empresa_provincia', sa.String(length=255), nullable=False),
    sa.Column('empresa_pais', sa.String(length=255), nullable=False),
    sa.Column('empresa_telefono', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('empresa_id')
    )
    op.create_table('productos',
    sa.Column('producto_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('producto_nombre', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('producto_id')
    )
    op.create_table('choferes',
    sa.Column('chofer_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rfid_uid', sa.String(length=255), nullable=True),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('apellido', sa.String(length=255), nullable=False),
    sa.Column('dni', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('habilitado', sa.Boolean(), nullable=False),
    sa.Column('created_on', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.empresa_id'], ),
    sa.PrimaryKeyConstraint('chofer_id')
    )
    op.create_table('silos',
    sa.Column('silo_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=True),
    sa.Column('capacidad', sa.Integer(), nullable=False),
    sa.Column('utilizado', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.producto_id'], ),
    sa.PrimaryKeyConstraint('silo_id')
    )
    op.create_table('vehiculos',
    sa.Column('vehiculo_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patente', sa.String(), nullable=False),
    sa.Column('seguro', sa.String(length=255), nullable=False),
    sa.Column('modelo', sa.String(length=255), nullable=False),
    sa.Column('año', sa.Integer(), nullable=False),
    sa.Column('marca', sa.String(length=255), nullable=False),
    sa.Column('habilitado', sa.Boolean(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.empresa_id'], ),
    sa.PrimaryKeyConstraint('vehiculo_id'),
    sa.UniqueConstraint('patente')
    )
    op.create_table('pesadasIn',
    sa.Column('pesada_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fecha_hora_in', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('fecha_hora_out', sa.TIMESTAMP(), nullable=False),
    sa.Column('chofer_id', sa.Integer(), nullable=True),
    sa.Column('peso_bruto_in', sa.DECIMAL(precision=9, scale=2), nullable=False),
    sa.Column('peso_bruto_out', sa.DECIMAL(precision=9, scale=2), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('producto_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chofer_id'], ['choferes.chofer_id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.empresa_id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.producto_id'], ),
    sa.PrimaryKeyConstraint('pesada_id')
    )
    op.create_table('turnos',
    sa.Column('turno_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_on', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('turno_fecha', sa.TIMESTAMP(), nullable=False),
    sa.Column('cantidad_estimada', sa.Integer(), nullable=False),
    sa.Column('chofer_id', sa.Integer(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('producto_id', sa.Integer(), nullable=True),
    sa.Column('vehiculo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chofer_id'], ['choferes.chofer_id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.empresa_id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.producto_id'], ),
    sa.ForeignKeyConstraint(['vehiculo_id'], ['vehiculos.vehiculo_id'], ),
    sa.PrimaryKeyConstraint('turno_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('turnos')
    op.drop_table('pesadasIn')
    op.drop_table('vehiculos')
    op.drop_table('silos')
    op.drop_table('choferes')
    op.drop_table('productos')
    op.drop_table('empresas')
    # ### end Alembic commands ###
