FROM python:3.12
WORKDIR /code
COPY ./requirements/development.txt /code/requirements.txt
RUN pip install -r /code/requirements.txt
# COPY ./api-sivrg.crt /code/
# COPY ./api-sivrg.key /code/
COPY . /code/

RUN adduser --system --no-create-home code
RUN chmod -R 777 /code/migrations
USER code
CMD ["uvicorn", "main:app", "--proxy-headers", "--host", "0.0.0.0", "--port", "8000"]
