"""Add empresa email

Revision ID: aa3374c60803
Revises: 8aa27270ed05
Create Date: 2023-10-26 02:19:30.001098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa3374c60803'
down_revision: Union[str, None] = '8aa27270ed05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empresas', sa.Column('empresa_email', sa.String(length=255), nullable=False, server_default='CHANGE@ME.com'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('empresas', 'empresa_email')
    # ### end Alembic commands ###
