"""Change table pesadasin name

Revision ID: 8aa27270ed05
Revises: a48650488587
Create Date: 2023-10-19 21:58:21.678178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8aa27270ed05"
down_revision: Union[str, None] = "a48650488587"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("pesadasIn", "pesadas")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("pesadas", "pesadasIn")

    # ### end Alembic commands ###
